name: "nyc_taxi_elt_pipeline"
version: "1.0.0"
config-version: 2

profile: "nyc_taxi"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:
    - target
    - dbt_packages

models:
  nyc_taxi_elt_pipeline:
    +materialized: view
    
    staging:
      +materialized: table
      +schema: staging

    intermediate:
      +materialized: ephemeral
    
    marts:
      +materialized: table
      +schema: marts