name: "nyc_taxi_elt_pipeline"
version: "1.0.0"
config-version: 2

profile: "nyc_taxi"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
    - target
    - dbt_packages

models:
  nyc_taxi_elt_pipeline:
    +materialized: view
    
    staging:
      +materialized: view
      +schema: staging
    
    marts:
      +materialized: table
      +schema: marts